apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: default
spec:
  type: NodePort               # Expose it outside cluster
  selector:
    app: my-app                # Match pods with label "app=my-app"
  ports:
    - port: 8080               # Service port inside cluster
      targetPort: 8080         # Forward to container’s port 8080
      nodePort: 30080          # External port (browser access: <NodeIP>:30080)
